### ISSUE TITLE
`listLatestRawPrices` seems to be flaky

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#375]
#### What happened:

`listLatestRawPrices` seems to be flaky, should investigate.

https://github.com/DeFiCh/jellyfish/pull/374/checks?check_run_id=2808796638

<details>
<summary><b>Error Summary</b></summary>

```diff
FAIL packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts (35.277 s)
  ● Oracle › should listLatestRawPrices with various timestamps

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -3,9 +3,9 @@
        "priceFeeds": Object {
          "currency": "EUR",
          "token": "APPLE",
        },
        "rawprice": "1.5",
    -   "state": "expired",
    +   "state": "live",
        "timestamp": "1623487546",
        "weightage": "3",
      }

      174 |     const result3 = data.find(element => element.oracleid === oracleid3)
      175 |
    > 176 |     expect(result3).toStrictEqual(
          |                     ^
      177 |       {
      178 |         priceFeeds: priceFeed,
      179 |         oracleid: oracleid3,

      at packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:176:21
      at fulfilled (packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:5:58)
          at runMicrotasks (<anonymous>)

  ● Oracle › should listLatestRawPrices with empty array if there is no oracle appointed

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 0
    Received: 5

      221 |     const data = await client.oracle.listLatestRawPrices()
      222 |
    > 223 |     expect(data.length).toStrictEqual(0)
          |                         ^
      224 |   })
      225 |
      226 |   it('should listLatestRawPrices with priceFeed as input parameter', async () => {

      at packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:223:25
      at fulfilled (packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:5:58)
          at runMicrotasks (<anonymous>)

  ● Oracle › should listLatestRawPrices with priceFeed as input parameter

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  -  0
    + Received  + 55

      Array [
        Object {
    +     "oracleid": "1589fbea5e4856159692ef6d08f1a5547655a455f1c9cebf8328bd79d6a46a0b",
    +     "priceFeeds": Object {
    +       "currency": "EUR",
    +       "token": "APPLE",
    +     },
    +     "rawprice": "2",
    +     "state": "expired",
    +     "timestamp": "1623480347",
    +     "weightage": "4",
    +   },
    +   Object {
    +     "oracleid": "a717d842e7e458c28067635742c1749b54899e2974816e5167dbb47ee123742d",
    +     "priceFeeds": Object {
    +       "currency": "EUR",
    +       "token": "APPLE",
    +     },
    +     "rawprice": "2.5",
    +     "state": "expired",
    +     "timestamp": "1623480346",
    +     "weightage": "5",
    +   },
    +   Object {
    +     "oracleid": "43f4fa616f66643aa4d4fb6ccfbca9ee2270a7a2e67f41d02b911d6ab7edc848",
    +     "priceFeeds": Object {
    +       "currency": "EUR",
    +       "token": "APPLE",
    +     },
    +     "rawprice": "0.5",
    +     "state": "live",
    +     "timestamp": "1623483946",
    +     "weightage": "1",
    +   },
    +   Object {
    +     "oracleid": "8813ac6e8ebb2b49f47a88e4731e059d0ad3402805bf3e5636c2745090732277",
    +     "priceFeeds": Object {
    +       "currency": "EUR",
    +       "token": "APPLE",
    +     },
    +     "rawprice": "1",
    +     "state": "live",
    +     "timestamp": "1623487545",
    +     "weightage": "2",
    +   },
    +   Object {
          "oracleid": "b1f615c75b6593b6f080b3916238c760afe5222e05ed35f3f680ef89cca46d7f",
          "priceFeeds": Object {
            "currency": "EUR",
            "token": "APPLE",
          },
          "rawprice": "0.5",
          "state": "live",
          "timestamp": "1623483947",
          "weightage": "1",
    +   },
    +   Object {
    +     "oracleid": "41e7b449d85d3fc9dc1fa3bf0aa68447dc74c415b5c774171cd73f3ad0be1db0",
    +     "priceFeeds": Object {
    +       "currency": "EUR",
    +       "token": "APPLE",
    +     },
    +     "rawprice": "1.5",
    +     "state": "live",
    +     "timestamp": "1623487546",
    +     "weightage": "3",
        },
      ]

      240 |     const data = await client.oracle.listLatestRawPrices(priceFeed)
      241 |
    > 242 |     expect(data).toStrictEqual(
          |                  ^
      243 |       [
      244 |         {
      245 |           priceFeeds: priceFeed,

      at packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:242:18
      at fulfilled (packages/jellyfish-api-core/__tests__/category/oracle/listLatestRawPrices.test.ts:5:58)
          at runMicrotasks (<anonymous>)
```

</details>

#### What you expected to happen:

Not have an error.

/area jellyfish-api-core
/triage accepted
/assign @jingyi2811

**Comment by jingyi2811** [comment]
Glad you found the problem. 

I have improved the code in the latest `getPrices` branch. 

See https://github.com/DeFiCh/jellyfish/pull/352#discussion_r650371705.

**Comment by jingyi2811** [comment]
I roughly know why did that happen. The test failed because oracles were not removed properly. I will change the way I write the tests.

**Comment by jingyi2811** [comment]
I have fixed this. See  
https://github.com/DeFiCh/jellyfish/pull/355/commits/5f4537cc1912093b8bdb649ec4f129529fb6c00f

**Comment by jingyi2811** [comment]
I have improved the code. The new code look like this.

```
beforeEach(async () => {
    await container.start()
    await container.waitForReady()
    await container.waitForWalletCoinbaseMaturity()
  })

  afterEach(async () => {
    const data = await container.call('listoracles')

    for (let i = 0; i < data.length; i += 1) {
      await container.call('removeoracle', [data[i]])
    }

    await container.generate(1)
  })

  afterAll(async () => {
    await container.stop()
  })
```
